/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carsalesclient.form;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author user
 */
public class MainForm extends javax.swing.JFrame {
    
    public MainForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        //this.setResizable(false);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblMain = new javax.swing.JLabel();
        btnSell = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInvoice = new javax.swing.JMenu();
        menuItemCreateNewInvoice = new javax.swing.JMenuItem();
        menuItemSeeAllInvoices = new javax.swing.JMenuItem();
        menuSalespersons = new javax.swing.JMenu();
        menuItemAddSalesman = new javax.swing.JMenuItem();
        menuItemSeeAllSalesmen = new javax.swing.JMenuItem();
        menuCars = new javax.swing.JMenu();
        menuItemAddNewCar = new javax.swing.JMenuItem();
        menuItemSeeAllCars = new javax.swing.JMenuItem();
        menuCustomers = new javax.swing.JMenu();
        menuItemAddNewCustomer = new javax.swing.JMenuItem();
        menuItemSeeAllCustomers = new javax.swing.JMenuItem();
        menuOptions = new javax.swing.JMenu();
        menuItemLanguage = new javax.swing.JMenu();
        menuItemEnglish = new javax.swing.JCheckBoxMenuItem();
        menuItemSerbian = new javax.swing.JCheckBoxMenuItem();
        menuItemLogOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Sales Tracker");
        setMinimumSize(new java.awt.Dimension(1350, 860));

        jLayeredPane2.setLayout(new javax.swing.OverlayLayout(jLayeredPane2));

        jPanel1.setOpaque(false);

        lblImage.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carsalesclient/form/images/mainFormImageNew.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblImage))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLayeredPane2.add(jPanel1);

        jPanel2.setOpaque(false);

        lblMain.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblMain.setText("jLabel1");

        btnSell.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnSell.setText("Sell Car");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMain, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSell, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(428, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblMain, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSell, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(561, Short.MAX_VALUE))
        );

        jLayeredPane2.add(jPanel2);

        menuInvoice.setText("Invoice");
        menuInvoice.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        menuItemCreateNewInvoice.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        menuItemCreateNewInvoice.setText("Create new invoice");
        menuItemCreateNewInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCreateNewInvoiceActionPerformed(evt);
            }
        });
        menuInvoice.add(menuItemCreateNewInvoice);

        menuItemSeeAllInvoices.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        menuItemSeeAllInvoices.setText("See all invoices");
        menuInvoice.add(menuItemSeeAllInvoices);

        jMenuBar1.add(menuInvoice);

        menuSalespersons.setText("Salesmen");
        menuSalespersons.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        menuItemAddSalesman.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        menuItemAddSalesman.setText("Add new salesman");
        menuSalespersons.add(menuItemAddSalesman);

        menuItemSeeAllSalesmen.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        menuItemSeeAllSalesmen.setText("See all salesmen");
        menuItemSeeAllSalesmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSeeAllSalesmenActionPerformed(evt);
            }
        });
        menuSalespersons.add(menuItemSeeAllSalesmen);

        jMenuBar1.add(menuSalespersons);

        menuCars.setText("Cars");
        menuCars.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        menuItemAddNewCar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        menuItemAddNewCar.setText("Add new car");
        menuItemAddNewCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddNewCarActionPerformed(evt);
            }
        });
        menuCars.add(menuItemAddNewCar);

        menuItemSeeAllCars.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        menuItemSeeAllCars.setText("See all cars");
        menuItemSeeAllCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSeeAllCarsActionPerformed(evt);
            }
        });
        menuCars.add(menuItemSeeAllCars);

        jMenuBar1.add(menuCars);

        menuCustomers.setText("Customers");
        menuCustomers.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        menuItemAddNewCustomer.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        menuItemAddNewCustomer.setText("Add new customer");
        menuItemAddNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddNewCustomerActionPerformed(evt);
            }
        });
        menuCustomers.add(menuItemAddNewCustomer);

        menuItemSeeAllCustomers.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        menuItemSeeAllCustomers.setText("See all customers");
        menuItemSeeAllCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSeeAllCustomersActionPerformed(evt);
            }
        });
        menuCustomers.add(menuItemSeeAllCustomers);

        jMenuBar1.add(menuCustomers);

        menuOptions.setText("Options");
        menuOptions.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        menuItemLanguage.setText("Language");
        menuItemLanguage.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        menuItemEnglish.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        menuItemEnglish.setSelected(true);
        menuItemEnglish.setText("English");
        menuItemLanguage.add(menuItemEnglish);

        menuItemSerbian.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        menuItemSerbian.setText("Српски");
        menuItemLanguage.add(menuItemSerbian);

        menuOptions.add(menuItemLanguage);

        menuItemLogOut.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        menuItemLogOut.setText("Log out");
        menuOptions.add(menuItemLogOut);

        jMenuBar1.add(menuOptions);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSeeAllCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSeeAllCarsActionPerformed
    }//GEN-LAST:event_menuItemSeeAllCarsActionPerformed

    private void menuItemSeeAllSalesmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSeeAllSalesmenActionPerformed
    }//GEN-LAST:event_menuItemSeeAllSalesmenActionPerformed

    private void menuItemAddNewCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddNewCarActionPerformed
    }//GEN-LAST:event_menuItemAddNewCarActionPerformed

    private void menuItemAddNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddNewCustomerActionPerformed
    }//GEN-LAST:event_menuItemAddNewCustomerActionPerformed

    private void menuItemSeeAllCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSeeAllCustomersActionPerformed
    }//GEN-LAST:event_menuItemSeeAllCustomersActionPerformed

    private void menuItemCreateNewInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCreateNewInvoiceActionPerformed
    }//GEN-LAST:event_menuItemCreateNewInvoiceActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSell;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblMain;
    private javax.swing.JMenu menuCars;
    private javax.swing.JMenu menuCustomers;
    private javax.swing.JMenu menuInvoice;
    private javax.swing.JMenuItem menuItemAddNewCar;
    private javax.swing.JMenuItem menuItemAddNewCustomer;
    private javax.swing.JMenuItem menuItemAddSalesman;
    private javax.swing.JMenuItem menuItemCreateNewInvoice;
    private javax.swing.JCheckBoxMenuItem menuItemEnglish;
    private javax.swing.JMenu menuItemLanguage;
    private javax.swing.JMenuItem menuItemLogOut;
    private javax.swing.JMenuItem menuItemSeeAllCars;
    private javax.swing.JMenuItem menuItemSeeAllCustomers;
    private javax.swing.JMenuItem menuItemSeeAllInvoices;
    private javax.swing.JMenuItem menuItemSeeAllSalesmen;
    private javax.swing.JCheckBoxMenuItem menuItemSerbian;
    private javax.swing.JMenu menuOptions;
    private javax.swing.JMenu menuSalespersons;
    // End of variables declaration//GEN-END:variables

    public JCheckBoxMenuItem getMenuItemEnglish() {
        return menuItemEnglish;
    }
    
    public JCheckBoxMenuItem getMenuItemSerbian() {
        return menuItemSerbian;
    }
    
    public void miCreateNewInvoiceAddActionListener(ActionListener actionListener){
        menuItemCreateNewInvoice.addActionListener(actionListener);
    }
    
    public void miSeeAllInvoicesAddActionListener(ActionListener actionListener){
        menuItemSeeAllInvoices.addActionListener(actionListener);
    }
    
    public void miAddNewSalesmanAddActionListener(ActionListener actionListener){
        menuItemAddSalesman.addActionListener(actionListener);
    }
    
    public void miSeeAllSalesmenAddActionListener(ActionListener actionListener){
        menuItemSeeAllSalesmen.addActionListener(actionListener);
    }
    
    public void miAddNewCarAddActionListener(ActionListener actionListener){
        menuItemAddNewCar.addActionListener(actionListener);
    }
    
    public void miSeeAllCarsAddActionListener(ActionListener actionListener){
        menuItemSeeAllCars.addActionListener(actionListener);
    }
    
    public void miAddNewCustomerAddActionListener(ActionListener actionListener){
        menuItemAddNewCustomer.addActionListener(actionListener);
    }
    
    public void miSeeAllCustomersAddActionListener(ActionListener actionListener){
        menuItemSeeAllCustomers.addActionListener(actionListener);
    }
    
    public JLabel getLblMain() {
        return lblMain;
    }

    public JMenuItem getMenuItemCreateNewInvoice() {
        return menuItemCreateNewInvoice;
    }
    
    public void miEnglishAddActionListener(ActionListener actionListener){
        menuItemEnglish.addActionListener(actionListener);
    }
    
    public void miSerbianAddActionListener(ActionListener actionListener){
        menuItemSerbian.addActionListener(actionListener);
    }

    public JMenu getMenuCars() {
        return menuCars;
    }

    public JMenu getMenuCustomers() {
        return menuCustomers;
    }

    public JMenu getMenuInvoice() {
        return menuInvoice;
    }

    public JMenu getMenuOptions() {
        return menuOptions;
    }

    public JMenu getMenuSalespersons() {
        return menuSalespersons;
    }

    public JMenuItem getMenuItemAddNewCar() {
        return menuItemAddNewCar;
    }

    public JMenuItem getMenuItemAddNewCustomer() {
        return menuItemAddNewCustomer;
    }

    public JMenuItem getMenuItemAddSalesman() {
        return menuItemAddSalesman;
    }

    public JMenu getMenuItemLanguage() {
        return menuItemLanguage;
    }

    public JMenuItem getMenuItemSeeAllCars() {
        return menuItemSeeAllCars;
    }

    public JMenuItem getMenuItemSeeAllCustomers() {
        return menuItemSeeAllCustomers;
    }

    public JMenuItem getMenuItemSeeAllInvoices() {
        return menuItemSeeAllInvoices;
    }

    public JMenuItem getMenuItemSeeAllSalesmen() {
        return menuItemSeeAllSalesmen;
    }

    public JMenuItem getMenuItemLogOut() {
        return menuItemLogOut;
    }

    public JLabel getLblImage() {
        return lblImage;
    }

    public JButton getBtnSell() {
        return btnSell;
    }
    
    public void btnSellCarAddActionListener(ActionListener actionListener){
        btnSell.addActionListener(actionListener);
    }
}
